
#if defined _amxmodx_version_included
  #endinput
#endif
#define _amxmodx_version_included

#define AMXX_VERSION_TAG        ""
#define AMXX_VERSION_CSET       "1f09bd5"
#define AMXX_VERSION_MAJOR      "1"
#define AMXX_VERSION_MINOR      "9"
#define AMXX_VERSION_RELEASE    "0"
#define AMXX_VERSION_LOCAL_REV  "5247"
#define AMXX_VERSION            1.90
#define AMXX_VERSION_NUM        190

stock const AMXX_VERSION_STR[] = "1.9.0.5247";
    