
#if defined _amxmodx_version_included
  #endinput
#endif
#define _amxmodx_version_included

#define AMXX_VERSION_TAG            ""
#define AMXX_VERSION_CSET           "27f451a"
#define AMXX_VERSION_MAJOR          "1"
#define AMXX_VERSION_MAJOR_NUM      1
#define AMXX_VERSION_MINOR          "10"
#define AMXX_VERSION_MINOR_NUM      10
#define AMXX_VERSION_RELEASE        "0"
#define AMXX_VERSION_LOCAL_REV_NUM  5467
#define AMXX_VERSION_LOCAL_REV      "5467"
#define AMXX_VERSION                1.100
#define AMXX_VERSION_NUM            200

stock const AMXX_VERSION_STR[] = "1.10.0.5467";
    